
package ventanas;

import codigo.cod_Dashboard;
import codigo.cod_bitacoras;
import codigo.cod_orden;
import codigo.cod_usuario;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import popup.Login;

/**
 *
 * @author Miguel
 */
public class Dashboard extends javax.swing.JFrame {

   
    private cod_usuario usuario = new cod_usuario();
    CardLayout cardLayout;
    private final boolean loginR; //valor para si se requerira login en cada pantalla
    private int tOrden; //1 si es nueva, 2 si es modificar, 3 si es agregar produ - Para el boton guardar
    private String ventana; //la ventana que este actualmente visible
    private final ArrayList<String> prodEliminados = new ArrayList<>();
    private String orden;
    
    
    
    public Dashboard(boolean login, cod_usuario user) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        cardLayout = (CardLayout)(this.panel3.getLayout());
        Dashboard();
        llevar();
        
        loginR = login;
        usuario = user;
        if (login==false) {
            this.jl_usuario.setText(usuario.getNombre());
        }
        ventana ="el sistema";
        registrarB(1);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_llevar = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JPanel();
        jtitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        panel_botones = new javax.swing.JPanel();
        btn_dashboard = new javax.swing.JButton();
        btn_orden = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_agregarProd = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_cobrar = new javax.swing.JButton();
        btn_estadisticas = new javax.swing.JButton();
        btn_administracion = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dashboard = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Orden = new javax.swing.JPanel();
        N_orden = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_mesero = new javax.swing.JTextField();
        tf_orden = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_cliente = new javax.swing.JTextField();
        cbx_mesa = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rd_no = new javax.swing.JRadioButton();
        rd_si = new javax.swing.JRadioButton();
        categorias = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_categoria = new javax.swing.JList<>();
        productos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        btn_eliminarfila2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        detalle_orden = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_detalleOrden = new javax.swing.JTable();
        btn_enviarOrden = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        btn_restarCantidad = new javax.swing.JButton();
        btn_sumarCantidad = new javax.swing.JButton();
        btn_eliminarfila = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Modificar = new javax.swing.JPanel();
        Cobrar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tf_Ctotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_cEntregado = new javax.swing.JFormattedTextField();
        tf_cPropina = new javax.swing.JFormattedTextField();
        tf_Cvuelto = new javax.swing.JFormattedTextField();
        btn_cCobrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        tf_Ccliente = new javax.swing.JTextField();
        tf_Cmesero = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_cobroDetalle = new javax.swing.JTable();
        jl_Corden = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jl_cobrarTitulo = new javax.swing.JLabel();
        btn_cerrarOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema POS");
        setMinimumSize(new java.awt.Dimension(1366, 768));

        titulo.setBackground(new java.awt.Color(179, 25, 18));

        jtitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtitulo.setText("Sistema POS");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario.png"))); // NOI18N
        jLabel1.setToolTipText("salir");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jl_usuario.setBackground(new java.awt.Color(255, 255, 255));
        jl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_usuario.setText("Usuario");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_botones.setBackground(new java.awt.Color(102, 102, 102));

        btn_dashboard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casa 32.png"))); // NOI18N
        btn_dashboard.setText("    Dashboard");
        btn_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_orden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo 32.png"))); // NOI18N
        btn_orden.setText("    Nueva orden");
        btn_orden.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_orden.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar 32.png"))); // NOI18N
        btn_modificar.setText("    Modificar");
        btn_modificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_agregarProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_agregarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas 32.png"))); // NOI18N
        btn_agregarProd.setText("    Agregar Producto");
        btn_agregarProd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_agregarProd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_agregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarProdActionPerformed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-de-impresion.png"))); // NOI18N
        btn_imprimir.setText("    Imprimir");
        btn_imprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_cobrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ahorrar-dinero.png"))); // NOI18N
        btn_cobrar.setText("    Cobrar");
        btn_cobrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cobrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cobrarActionPerformed(evt);
            }
        });

        btn_estadisticas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/grafico-de-barras (1).png"))); // NOI18N
        btn_estadisticas.setText("    Estadisticas");
        btn_estadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_estadisticas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estadisticasActionPerformed(evt);
            }
        });

        btn_administracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_administracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ajustes.png"))); // NOI18N
        btn_administracion.setText("    Administracion");
        btn_administracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_administracion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_botonesLayout = new javax.swing.GroupLayout(panel_botones);
        panel_botones.setLayout(panel_botonesLayout);
        panel_botonesLayout.setHorizontalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_orden, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_agregarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_cobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_estadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_administracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_botonesLayout.setVerticalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botonesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_agregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_administracion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel3.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Filtrar:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Buscar:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tb_dashboard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_dashboard.setRowHeight(25);
        tb_dashboard.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tb_dashboard);

        jButton1.setText("Dashboard para llevar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DashboardLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(23, 23, 23))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        panel3.add(Dashboard, "Dashboard");

        N_orden.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mesero:");

        tf_mesero.setEditable(false);
        tf_mesero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_orden.setEditable(false);
        tf_orden.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Orden:  #");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Mesa:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Cliente");

        tf_cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_clienteActionPerformed(evt);
            }
        });

        cbx_mesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbx_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Para llevar:");

        rd_no.setText("No");

        rd_si.setText("Si");
        rd_si.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd_siStateChanged(evt);
            }
        });

        javax.swing.GroupLayout N_ordenLayout = new javax.swing.GroupLayout(N_orden);
        N_orden.setLayout(N_ordenLayout);
        N_ordenLayout.setHorizontalGroup(
            N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N_ordenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(N_ordenLayout.createSequentialGroup()
                        .addComponent(rd_si)
                        .addGap(18, 18, 18)
                        .addComponent(rd_no)))
                .addGap(38, 38, 38)
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_mesero, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        N_ordenLayout.setVerticalGroup(
            N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N_ordenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(tf_mesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(rd_si)
                    .addComponent(rd_no))
                .addGap(10, 10, 10)
                .addGroup(N_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbx_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Categorias:");

        list_categoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list_categoria.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_categoria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_categoria.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_categoriaValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(list_categoria);

        javax.swing.GroupLayout categoriasLayout = new javax.swing.GroupLayout(categorias);
        categorias.setLayout(categoriasLayout);
        categoriasLayout.setHorizontalGroup(
            categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        categoriasLayout.setVerticalGroup(
            categoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(146, 146, 146))
        );

        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Preparacion", "Inventario"
            }
        ));
        tb_productos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tb_productos);

        btn_eliminarfila2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_eliminarfila2.setForeground(new java.awt.Color(0, 0, 255));
        btn_eliminarfila2.setText("->");
        btn_eliminarfila2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eliminarfila2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarfila2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Productos:");

        javax.swing.GroupLayout productosLayout = new javax.swing.GroupLayout(productos);
        productos.setLayout(productosLayout);
        productosLayout.setHorizontalGroup(
            productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productosLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminarfila2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(productosLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        productosLayout.setVerticalGroup(
            productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(36, 36, 36)
                .addGroup(productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_eliminarfila2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(146, 146, 146))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Detalle orden:");

        tb_detalleOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_detalleOrden.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb_detalleOrdenPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tb_detalleOrden);

        btn_enviarOrden.setText("Enviar orden");
        btn_enviarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarOrdenActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Total:");

        tf_total.setEditable(false);
        tf_total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btn_restarCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_restarCantidad.setText("-");
        btn_restarCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_restarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarCantidadActionPerformed(evt);
            }
        });

        btn_sumarCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_sumarCantidad.setText("+");
        btn_sumarCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sumarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarCantidadActionPerformed(evt);
            }
        });

        btn_eliminarfila.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_eliminarfila.setText("---");
        btn_eliminarfila.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eliminarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarfilaActionPerformed(evt);
            }
        });

        jButton10.setText("Cobrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detalle_ordenLayout = new javax.swing.GroupLayout(detalle_orden);
        detalle_orden.setLayout(detalle_ordenLayout);
        detalle_ordenLayout.setHorizontalGroup(
            detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalle_ordenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalle_ordenLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))
                    .addGroup(detalle_ordenLayout.createSequentialGroup()
                        .addGroup(detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(detalle_ordenLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_eliminarfila, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sumarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_restarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detalle_ordenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_enviarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        detalle_ordenLayout.setVerticalGroup(
            detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalle_ordenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addGroup(detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalle_ordenLayout.createSequentialGroup()
                        .addComponent(btn_sumarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_restarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminarfila, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(detalle_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout OrdenLayout = new javax.swing.GroupLayout(Orden);
        Orden.setLayout(OrdenLayout);
        OrdenLayout.setHorizontalGroup(
            OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdenLayout.createSequentialGroup()
                .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrdenLayout.createSequentialGroup()
                        .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(detalle_orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(N_orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        OrdenLayout.setVerticalGroup(
            OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenLayout.createSequentialGroup()
                .addComponent(N_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detalle_orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel3.add(Orden, "Orden");
        Orden.getAccessibleContext().setAccessibleParent(Orden);

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar);
        Modificar.setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1157, Short.MAX_VALUE)
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        panel3.add(Modificar, "Modificar");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Total:");

        tf_Ctotal.setEditable(false);
        tf_Ctotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Total entregado:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Propina:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Vuelto:");

        tf_cEntregado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        tf_cEntregado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_cEntregado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_cEntregadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cEntregadoKeyTyped(evt);
            }
        });

        tf_cPropina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        tf_cPropina.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tf_Cvuelto.setEditable(false);
        tf_Cvuelto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        tf_Cvuelto.setText("0.0");
        tf_Cvuelto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btn_cCobrar.setText("Cobrar");
        btn_cCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_Cvuelto, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_Ctotal, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_cEntregado)
                            .addComponent(tf_cPropina)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_Ctotal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_cEntregado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cPropina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Cvuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btn_cCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Cliente:");

        tf_Ccliente.setEditable(false);

        tf_Cmesero.setEditable(false);

        jLabel21.setText("Mesero:");

        tb_cobroDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cnt", "Prod.", "Precio", "Total"
            }
        ));
        jScrollPane5.setViewportView(tb_cobroDetalle);

        jl_Corden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_Corden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Corden.setText("Orden #");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Corden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tf_Cmesero))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Ccliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jl_Corden)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_Ccliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(tf_Cmesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        jl_cobrarTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_cobrarTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_cobrarTitulo.setText("Orden ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_cobrarTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_cobrarTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_cerrarOrden.setText("Cerrar orden");
        btn_cerrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CobrarLayout = new javax.swing.GroupLayout(Cobrar);
        Cobrar.setLayout(CobrarLayout);
        CobrarLayout.setHorizontalGroup(
            CobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CobrarLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(CobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cerrarOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        CobrarLayout.setVerticalGroup(
            CobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CobrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CobrarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(CobrarLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cerrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        panel3.add(Cobrar, "Cobrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
        this.Dashboard();

    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenActionPerformed
        //nueva orden
        ventana = "orden nueva";
        tOrden =1;
        login(true, "Orden", 1);    
    }//GEN-LAST:event_btn_ordenActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // ***Modificar***
        if (tb_dashboard.getSelectedRow()!=-1) {
            login(false, "Orden", 2);
            tOrden =2;
            
        }    
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_agregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarProdActionPerformed
        // **agregar producto
        if (tb_dashboard.getSelectedRow()!=-1) {
            tOrden =3;
            login(true, "Orden", 3);
        }
    }//GEN-LAST:event_btn_agregarProdActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_cobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cobrarActionPerformed
        // cobrar orden
        if (tb_dashboard.getSelectedRow()!=-1) {
            login(true, "Cobrar", 4);
        }
    }//GEN-LAST:event_btn_cobrarActionPerformed

    private void btn_estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estadisticasActionPerformed
        // TODO add your handling code here:
        Estadisticas a = new Estadisticas();
        a.setVisible(true);
    }//GEN-LAST:event_btn_estadisticasActionPerformed

    private void btn_administracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administracionActionPerformed
        // TODO add your handling code here:
        Administracion a = new Administracion();
        
        a.setVisible(true);
        //dispose();
    }//GEN-LAST:event_btn_administracionActionPerformed

    private void btn_restarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarCantidadActionPerformed
        // TODO add your handling code here:
        if (tb_detalleOrden.getSelectedRow()!=-1) {
            this.ModificarCantidad(-1.0, tb_detalleOrden.getSelectedRow());
            this.total();
        }
        
    }//GEN-LAST:event_btn_restarCantidadActionPerformed

    private void btn_sumarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarCantidadActionPerformed
        // TODO add your handling code here:
        if (tb_detalleOrden.getSelectedRow()!=-1) {
            this.ModificarCantidad(1.0, tb_detalleOrden.getSelectedRow());
            this.total();
        }
        
    }//GEN-LAST:event_btn_sumarCantidadActionPerformed

    private void btn_eliminarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarfilaActionPerformed
         
        if (tb_detalleOrden.getSelectedRow()!=-1) {
            if (tOrden==2) {
                this.prodEliminados.add(tb_detalleOrden.getValueAt(tb_detalleOrden.getSelectedRow(), 0).toString());
            }
            
            DefaultTableModel md = new DefaultTableModel();
            md = (DefaultTableModel) tb_detalleOrden.getModel();
            md.removeRow(tb_detalleOrden.getSelectedRow());
            this.total(); 
        }
        
    }//GEN-LAST:event_btn_eliminarfilaActionPerformed

    private void btn_eliminarfila2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarfila2ActionPerformed
        // TODO add your handling code here:
        detalle_orden(tb_productos.getSelectedRow());
        this.total();
    }//GEN-LAST:event_btn_eliminarfila2ActionPerformed

    private void tf_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_clienteActionPerformed

    private void list_categoriaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_categoriaValueChanged
        productos(this.list_categoria.getSelectedValue());
    }//GEN-LAST:event_list_categoriaValueChanged

    private void tb_detalleOrdenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb_detalleOrdenPropertyChange
        this.total();
    }//GEN-LAST:event_tb_detalleOrdenPropertyChange

    private void rd_siStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd_siStateChanged
        // TODO add your handling code here:
        if (rd_si.isSelected()==true) {
            this.cbx_mesa.setEnabled(false);
        } else {
            this.cbx_mesa.setEnabled(true);
        }
    }//GEN-LAST:event_rd_siStateChanged

    private void btn_enviarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarOrdenActionPerformed
        // TODO add your handling code here:
        switch (tOrden){
            case 1:
                if (validarOrden()==true) {
                    this.guardarOrden();
                    Dashboard();
                }
                break;
            case 2:
                guardarOrdenModif();
                break;
            case 3:
                agregarProductos();
                break;
        }
        
    }//GEN-LAST:event_btn_enviarOrdenActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
        Inicio a = new Inicio();
        a.iniciar();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void btn_cCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cCobrarActionPerformed
        // 
        cobrarOrden();
    }//GEN-LAST:event_btn_cCobrarActionPerformed

    private void tf_cEntregadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cEntregadoKeyTyped
            
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){
            evt.consume();
        }
        
    }//GEN-LAST:event_tf_cEntregadoKeyTyped

    private void tf_cEntregadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cEntregadoKeyReleased
        // TODO add your handling code here:
        double total = Double.parseDouble(tf_Ctotal.getText());
        double rs=0.0;
        try {
            double entreg = Double.parseDouble(tf_cEntregado.getText());
            rs = -total + entreg;
        } catch (Exception e) {
        }
        
        
        tf_Cvuelto.setText(String.valueOf(rs));
    }//GEN-LAST:event_tf_cEntregadoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard_llevar a = new Dashboard_llevar();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

    }//GEN-LAST:event_jButton10ActionPerformed

    private void btn_cerrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarOrdenActionPerformed
        // TODO add your handling code here:
        cod_orden.cerrarOrden(orden);
        bitacoraOrden(5);
    }//GEN-LAST:event_btn_cerrarOrdenActionPerformed

    
    
    
    /**************************************************************************
                               Metodos para orden
    ***************************************************************************/
    private void nueva_orden(){
        panelesOrden(true, true, true, true);
        lista_Categoria();
        mesas();
        tabla_detalle();
        n_orden(cod_orden.ordenId());
        tf_mesero.setText(usuario.getNombre());
        
    }
    private void modificar_orden(String orden){
        panelesOrden(true, false, false, true);
        tabla_detalle();
        prodEliminados.clear();
        traerOrden(tb_dashboard.getSelectedRow());
    }
    private void agregar_aOrden(String orden){
        panelesOrden(false, true, true, true);
        lista_Categoria();
        tabla_detalle();
    }
    
    
    
    private void lista_Categoria(){
        this.list_categoria.setModel(cod_orden.lst_Categorias());
    }
    private void mesas(){
        this.cbx_mesa.setModel(cod_orden.llenar_cbx());
    }
    private void productos(String x){
        this.tb_productos.setModel(cod_orden.llenarTabla(x));
    }
    private void detalle_orden(int x){
        this.tb_detalleOrden.setModel(cod_orden.detalleOrden(x, (DefaultTableModel) tb_productos.getModel(), (DefaultTableModel) tb_detalleOrden.getModel()));
    }
    private void ModificarCantidad(double v, int fila){
        this.tb_detalleOrden.setModel(cod_orden.cantidad(v, fila, (DefaultTableModel)tb_detalleOrden.getModel()));
    }
    private void tabla_detalle(){
        tb_detalleOrden.setModel(cod_orden.detalleOrden());
    }
    private void total(){
        this.tf_total.setText(cod_orden.Total((DefaultTableModel)tb_detalleOrden.getModel()));
    }
    
    
    //metodos para visualizar los paneles de ordenes
    private void panelesOrden(boolean titulo, boolean categoria, boolean producto, boolean detalle){
        this.N_orden.setVisible(titulo);
        this.categorias.setVisible(categoria);
        this.productos.setVisible(producto);
        this.detalle_orden.setVisible(detalle);
    }
    
    private void n_orden(String n){
        this.tf_orden.setText(n);
        orden=n;
    }
    private void llevar(){
        this.rb_llevar.add(rd_no);
        this.rb_llevar.add(rd_si);
        
        rd_no.setSelected(true);
    }
    
    
    //guardar orden
    private void guardarOrden(){
        
        cod_orden x = new cod_orden();
        x.setCliente(tf_cliente.getText());
        x.setIdUsuario(usuario.getId());
        x.setId(tf_orden.getText());
        x.setTotal(tf_total.getText());
        x.setEstado("AA");
        
        if (rd_no.isSelected()==true) {
            x.setLlevar("0");
            x.setIdMesa(cbx_mesa.getSelectedItem().toString());
            cod_orden.guardar(x, (DefaultTableModel) tb_detalleOrden.getModel());
        }else {
            x.setLlevar("1");
            cod_orden.guardar2(x, (DefaultTableModel) tb_detalleOrden.getModel());
        }
        
        bitacoraOrden(1);
    }
    
    
    
    /************************************************************************
                        Dashboard Principal
    ************************************************************************/
    private void Dashboard(){
        cardLayout.show(panel3, "Dashboard");
        tb_dashboard.setModel(cod_Dashboard.llenarTabla());
        activarMenu(true);
        this.jtitulo.setText("Dashboard");
        ventana = "Dashboard";
    }
    
    /***********************************************************************
     *                     Modficiar orden
    ************************************************************************/
    
    private void traerOrden(int row){
        mesas();
        String orden = tb_dashboard.getValueAt(row, 0).toString();
        
        
        tb_detalleOrden.setModel((DefaultTableModel) cod_orden.tabla_detalleOrden(orden));
        
        tf_cliente.setText(tb_dashboard.getValueAt(row, 2).toString());
        tf_mesero.setText(tb_dashboard.getValueAt(row, 3).toString());
        tf_orden.setText(orden);
        tf_total.setText(tb_dashboard.getValueAt(row, 4).toString());

        int x = Integer.parseInt(tb_dashboard.getValueAt(row, 6).toString());

        if (x==0) {
            rd_no.setSelected(true);
            cbx_mesa.setSelectedIndex(Integer.parseInt(tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 1).toString())-1);
        }else{
            rd_si.setSelected(true);
        }
    
    }
    
    private void guardarOrdenModif(){
        
        cod_orden x = new cod_orden();
        
        x.setCliente(tf_cliente.getText());
        x.setTotal(tf_total.getText());
        
        if (rd_no.isSelected()==true) {
            x.setLlevar("0");
            x.setIdMesa(cbx_mesa.getSelectedItem().toString());
            
            
        }else {
            x.setLlevar("1");     
        }
        
        cod_orden.guardaOrdenModif(x, prodEliminados, tf_orden.getText(), (DefaultTableModel) tb_detalleOrden.getModel());
        
        bitacoraOrden(2);
        Dashboard();
    }
    
    
    
    
    
    
    
    /**************************************************************************
                                         Cobrar
    **************************************************************************/
    private void Cobrar_panel(String orden){
        cardLayout.show(panel3, "Cobrar");
        activarMenu(false);
        this.jtitulo.setText("Cobrar orden #"+orden);
        jl_cobrarTitulo.setText("Orden #"+orden);
        
        jl_Corden.setText(orden);
        tf_Ccliente.setText(tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 2).toString());
        tf_Ctotal.setText(tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 4).toString());
        tf_Cmesero.setText(tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 3).toString());
        tablaCobro(orden);
        
        String estado = tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 5).toString();
        if (estado.equals("CP")) {
            cobrada(false);
            jl_cobrarTitulo.setText(jl_cobrarTitulo.getText() + " CANCELADA");
            btn_cerrarOrden.setVisible(true);
        } else{
            btn_cerrarOrden.setVisible(false);
            cobrada(true);
        }
    }
    
    private void tablaCobro(String orden){
        this.tb_cobroDetalle.setModel((DefaultTableModel) cod_orden.tabla_detalleOrden(orden));
    }
    
    private void cobrada(boolean a){
        tf_cEntregado.setEnabled(a);
        tf_cPropina.setEnabled(a);
        btn_cCobrar.setEnabled(a);      
    }
    
    private void cobrarOrden(){
        double v = 0;
        try {
            v = Double.parseDouble(tf_cEntregado.getText());
        } catch (Exception e) {
        }
        double t = Double.parseDouble(tf_Ctotal.getText());
        if (v>=t) {
           cod_orden.cobrar(jl_Corden.getText());
            cobrada(false);
            jl_cobrarTitulo.setText(jl_cobrarTitulo.getText() + " CANCELADA");
            bitacoraOrden(4);
        }
        
    }
    
    /**************************************************************************
     *                 Agregar nuevos productos a la orden existente
    **************************************************************************/
    private void agregarProductos(){
        double tt=Double.parseDouble(tf_total.getText());
        
        if (tt>0) {
            cod_orden.DetalleOrdenExistente((DefaultTableModel) tb_detalleOrden.getModel(), tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 0).toString(), tt, true);
              
        }
        bitacoraOrden(3);
        Dashboard();
    }
    
    
    
    
    
    
    /*************************************************************************
     *                  Registar bitacora
    *************************************************************************/
    private void registrarB(int tipo){
            cod_bitacoras x = new cod_bitacoras();
            x.setIdUsuario(this.usuario.getId());
            x.setSuceso(cod_bitacoras.tipoSeceso(ventana, tipo));
        
            cod_bitacoras.registrarBitacora(x);   
    }
    
    private void bitacoraOrden(int tipo){
        cod_bitacoras x = new cod_bitacoras();
            x.setIdUsuario(this.usuario.getId());
            x.setSuceso(cod_bitacoras.sucesoOrden(orden, tipo));
        
            cod_bitacoras.registrarBitacora(x);
    }
    
    
    
    
    /**************************************************************************
                        login para cada pantalla
    **************************************************************************/  
    private void login (boolean pin, String panel, int tipo){
        if (tb_dashboard.getSelectedRow()!= -1) {
            orden = tb_dashboard.getValueAt(tb_dashboard.getSelectedRow(), 0).toString();
        }
        
        if (loginR==true) {
            Login a = new Login(this, true);
        
            a.jl_titulo.setText("Identificarse");
            a.setLocationRelativeTo(null);
            a.modoPin(pin);
            a.setVisible(true);
        
            a.addWindowListener(new WindowAdapter(){
                @Override

                public void windowClosed(WindowEvent e){
                    usuario = a.Comprobar();
                    if (usuario.isEstado()==true) {
                        cardLayout.show(panel3, panel);
                        switch (tipo){
                            case 1:
                                jtitulo.setText("Nueva orden");
                                nueva_orden();
                                
                                registrarB(1);
                                break;
                            case 2:
                                jtitulo.setText("Modificar Orden");
                                
                                modificar_orden(orden);
                                break;
                            case 3:
                                jtitulo.setText("Agregar producto a la Orden #"+orden);
                                agregar_aOrden(orden);
                                break;
                            case 4:
                                Cobrar_panel(orden);
                                break;
                        }
                                
                        activarMenu(false);
                    }

                }
            }   
        );
            
        } else {
            cardLayout.show(panel3, panel);
            switch (tipo){
                
                            case 1:
                                jtitulo.setText("Nueva orden");
                                nueva_orden();
                                break;
                            case 2:
                                jtitulo.setText("Modificar Orden");
                                modificar_orden(orden);
                                break;
                            case 3:
                                jtitulo.setText("Agregar producto a la Orden #"+orden);
                                agregar_aOrden(orden);
                                break; 
                            case 4:
                                Cobrar_panel(orden);
                                break;
                        }
            activarMenu(false);
        }

    }
    
    private void activarMenu(boolean a){
        btn_orden.setEnabled(a);
        btn_modificar.setEnabled(a);
        btn_agregarProd.setEnabled(a);
        btn_cobrar.setEnabled(a);
        btn_imprimir.setEnabled(a);
        btn_administracion.setEnabled(a);
        btn_estadisticas.setEnabled(a);
    } 
    
    private boolean validarOrden(){
        if (tf_cliente.getText().equals("")==true) {
            System.out.println("Ingrese el cliente");
            return false;
        }
        return true;
    }

    
    
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cobrar;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Modificar;
    private javax.swing.JPanel N_orden;
    private javax.swing.JPanel Orden;
    private javax.swing.JButton btn_administracion;
    private javax.swing.JButton btn_agregarProd;
    private javax.swing.JButton btn_cCobrar;
    private javax.swing.JButton btn_cerrarOrden;
    private javax.swing.JButton btn_cobrar;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_eliminarfila;
    private javax.swing.JButton btn_eliminarfila2;
    private javax.swing.JButton btn_enviarOrden;
    private javax.swing.JButton btn_estadisticas;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_orden;
    private javax.swing.JButton btn_restarCantidad;
    private javax.swing.JButton btn_sumarCantidad;
    private javax.swing.JPanel categorias;
    private javax.swing.JComboBox<String> cbx_mesa;
    private javax.swing.JPanel detalle_orden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jl_Corden;
    private javax.swing.JLabel jl_cobrarTitulo;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JList<String> list_categoria;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel productos;
    private javax.swing.ButtonGroup rb_llevar;
    private javax.swing.JRadioButton rd_no;
    private javax.swing.JRadioButton rd_si;
    private javax.swing.JTable tb_cobroDetalle;
    private javax.swing.JTable tb_dashboard;
    private javax.swing.JTable tb_detalleOrden;
    private javax.swing.JTable tb_productos;
    private javax.swing.JTextField tf_Ccliente;
    private javax.swing.JTextField tf_Cmesero;
    private javax.swing.JTextField tf_Ctotal;
    private javax.swing.JFormattedTextField tf_Cvuelto;
    private javax.swing.JFormattedTextField tf_cEntregado;
    private javax.swing.JFormattedTextField tf_cPropina;
    private javax.swing.JTextField tf_cliente;
    private javax.swing.JTextField tf_mesero;
    private javax.swing.JTextField tf_orden;
    private javax.swing.JTextField tf_total;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
